services:
  - type: web
    name: rag-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port 10000
    envVars:
      - key: OPENAI_API_KEY
        value: your-openai-api-key-here
